# Generated by Django 3.0.8 on 2020-07-27 21:45

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('stripe_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='stripe ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='amount')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('GBP', 'British Pound')], default='USD', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('requires_action', 'Requires authentication'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled')], default='created', max_length=16, verbose_name='status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('product_id', models.CharField(max_length=64, verbose_name='product ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
